name: CI сборка для проекта

on:
  pull_request:
    branches:
      - 'master'
      - 'i[0-9]+-*'
  push:
    branches:
      - 'master'
      - 'i[0-9]+-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получить код
        uses: actions/checkout@v4

      - name: Установить Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Дать права на gradlew
        run: chmod +x gradlew

      - name: Запустить тесты
        run: ./gradlew test